### ISSUE TITLE
Add ability to run sequencer (astria sequencer + cometbft) only

### ISSUE THREAD

**Issue by sambukowski** [astriaorg/astria-cli-go#83]
This is currently possible by using the following command:
`astria-go dev run --composer-path="/bin/echo" --conductor-path="/bin/echo"`

This pr is for adding a new run flag alongside `--dusk`, `--dawn`, etc. (for example `--sequencer-only`) to simplify this particular use case, and have the TUI also only display logs for the sequencer and cometbft, instead of also having blank boxes for conductor and composer.

**Comment by sambukowski** [comment]
Closing this.
With the networks-config.toml changes, you can achieve this by creating a new custom network:
```toml
[networks.sequencer_only]
sequencer_chain_id = 'sequencer-only'
sequencer_grpc = 'http://127.0.0.1:8080'
sequencer_rpc = 'http://127.0.0.1:26657'
rollup_name = 'astria-test-chain'
default_denom = 'nria'

[networks.sequencer_only.services]
[networks.sequencer_only.services.cometbft]
name = 'cometbft'
version = 'v0.38.8'
download_url = 'https://github.com/cometbft/cometbft/releases/download/v0.38.8/cometbft_0.38.8_darwin_arm64.tar.gz'
local_path = '<your home directory>/.astria/default/bin/cometbft-v0.38.8'
args = []

[networks.sequencer_only.services.sequencer]
name = 'astria-sequencer'
version = 'v0.15.0'
download_url = 'https://github.com/astriaorg/astria/releases/download/sequencer-v0.15.0/astria-sequencer-aarch64-apple-darwin.tar.gz'
local_path = '<your home directory>/.astria/default/bin/astria-sequencer-v0.15.0'
args = []
```

Then running that network with:

```bash
astria-go dev init
astria-go dev run --network sequencer_only
```
