### ISSUE TITLE
Add a debug build to our release pipeline

### ISSUE THREAD

**Issue by steezeburger** [astriaorg/astria-cli-go#91]
The prod build removes the symbol table and DWARF debugging information.

We should add a debug build to our pipeline so that we have a binary that can be ran with a debugger for when we find a hard to solve bug in our production binary. Probably just:

```yaml
  build-for-debug:
    name: Build For Debug
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: "arm64"
            goos: "linux"
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: >
            -X github.com/astria/astria-cli-go/cmd.version=${{ github.ref_name }}
          project_path: "./"
          binary_name: "astria-go-debug"
```
